version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network
    environment:
      - QDRANT__SERVICE__PUBLIC_URL=https://qdrant.sbazar.in
      - QDRANT__SERVICE__HTTP_BIND=0.0.0.0:6333
      - QDRANT__SERVICE__GRPC_BIND=0.0.0.0:6334
      - QDRANT__SERVICE__API_KEY=your_secret_api_key_here
      

volumes:
  qdrant_storage:

networks:
  qdrant_network:
    driver: bridge
