version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network

volumes:
  qdrant_storage:

networks:
  qdrant_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
